# -*- coding: utf-8 -*-
"""Aula_8.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lu1jt6Pfa4p5TrJhclokJ_c06G2jxW1j
"""

my_tuple = (1,3,645,89,76,45)
my_indice = my_tuple[2]
print(my_indice)
my_tuple = my_tuple2 = (20,30,60,15,15)
my_tuple = my_tuple2
print(my_tuple)


tuple1 = (2,56,89,7,8,9)
print(tuple1)
transform = list(tuple1)
print(transform)
transformando tupla em lista

**EXERCÍCIOS:**

1 -  Crie uma tupla chamada `frutas` com pelo menos 5 frutas diferentes. Em seguida, acesse e imprima o terceiro elemento da tupla.

frutas = ("Morango","Kwui","Pera","Amora","Acerola")
print(frutas[3])

2 - Crie uma tupla chamada numeros com alguns números inteiros. Em seguida, converta essa tupla em uma lista e imprima a lista resultante.

numeros = (1,4,7,12,36,28,32)
numeros_lista = list(numeros)
print(numeros_lista)

3 - Crie uma tupla chamada `meses` com os nomes dos meses do ano até Setembro. Use um loop `for` para imprimir cada mês em uma linha separada.

meses = ("Janeiro","Feveriro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro")
for m in meses:
  print(m)

4 - Crie uma lista chamada notas com algumas notas de alunos. Em seguida, converta essa lista em uma tupla e imprima a tupla resultante.

notas = [4,8,12,18,20]
nota_tupla = tuple(notas)
print(nota_tupla)

5 - Crie uma lista chamada `ponto` que represente as coordenadas (x, y) de um ponto. Em seguida, desempacote os elementos da lista em duas variáveis separadas (x e y) e imprima os valores.

ponto = (20,28,60)
x,y,a = ponto
print("coordenada",x)
print("coordenada",y)
print("coordenada",a)